name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testsuite:
    name: all tests
    runs-on: ubuntu-latest
    steps:

      - name: "Extract information (overview)"
        shell: bash
        run: |
          # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
          echo "-------------------------------------------------------------------------------------------------------"
          echo "CI............................: ${CI}"
          echo "GITHUB_ACTION.................: ${GITHUB_ACTION}"
          echo "GITHUB_ACTION_PATH............: ${GITHUB_ACTION_PATH}"          
          echo "GITHUB_ACTIONS................: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR..................: ${GITHUB_ACTOR}"
          echo "GITHUB_ACTOR_ID...............: ${GITHUB_ACTOR_ID}"
          echo "GITHUB_API_URL................: ${GITHUB_API_URL}"          
          echo "GITHUB_ENV....................: ${GITHUB_ENV}"
          echo "GITHUB_JOB....................: ${GITHUB_JOB}"
          echo "-------------------------------------------------------------------------------------------------------"
          echo "GITHUB_EVENT_NAME.............: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_ACTION_REPOSITORY......: ${GITHUB_ACTION_REPOSITORY}"
          echo "GITHUB_REPOSITORY.............: ${GITHUB_REPOSITORY}"
          echo "GITHUB_BASE_REF...............: ${GITHUB_BASE_REF}"
          echo "GITHUB_HEAD_REF...............: ${GITHUB_HEAD_REF}"
          echo "GITHUB_REF....................: ${GITHUB_REF}"
          echo "GITHUB_REF_NAME...............: ${GITHUB_REF_NAME}"
          echo "GITHUB_REF_PROTECTED..........: ${GITHUB_REF_PROTECTED}"
          echo "GITHUB_REF_TYPE...............: ${GITHUB_REF_TYPE}"
          echo "-------------------------------------------------------------------------------------------------------"

#      - name: "Extract information (USE_CHECKOUT_REF)"
#        shell: bash
#        id: use_checkout_ref
#        run: |
#          USE_CHECKOUT_REF=''
#          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
#            USE_CHECKOUT_REF="${GITHUB_HEAD_REF}"
#          fi
#          echo "ref=${USE_CHECKOUT_REF}" >> $GITHUB_OUTPUT
#
#      - name: Checkout ${{ steps.use_checkout_ref.outputs.ref }}
#        uses: actions/checkout@v4
#        with:
#          ref: ${{ steps.use_checkout_ref.outputs.ref }}

      - name: Checkout ${{ github.event_name == 'workflow_dispatch' && github.head_ref || '' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.head_ref || '' }}

      - name: Output README.md
        shell: bash
        run: |
          cat README.md